subscription registryNotification {
  registryNotification {
    notificationName
    instrumentAddress
    instrumentLedger
    transactionHash
  }
}

#{
#  "data": {
#    "registryNotification": {
#      "notificationName": "InstrumentListed",
#      "instrumentAddress": "0x69DA398f9D7c2EA378dB2603B70A1be92B4351CF",
#      "instrumentLedger": "ETHEREUM",
#      "transactionHash": "0x0c912d1e6cc033785566afcc798847f0e6c3043d949de9b341eeaf45951b26ae"
#    }
#  }
#}
