export const SETTLEMENT_TRANSACTION_STATUS_NOT_CREATED = 0;
export const SETTLEMENT_TRANSACTION_STATUS_CREATED = 1;
export const SETTLEMENT_TRANSACTION_STATUS_TOKEN_LOCKED = 2;
export const SETTLEMENT_TRANSACTION_STATUS_CASH_RECEIVED = 3;
export const SETTLEMENT_TRANSACTION_STATUS_CASH_SENT = 4;
export const SETTLEMENT_TRANSACTION_STATUS_CANCELED = 5;
export const SETTLEMENT_TRANSACTION_STATUS_ERROR = 255;
