export const BLOCKCHAIN_USE_MOCK = 'BLOCKCHAIN_USE_MOCK';
export const CLAIM_EXP = 'CLAIM_EXP';

export enum TZ {
  BLOCKCHAIN_PROVIDE_LOCATION = 'TZ_BLOCKCHAIN_PROVIDE_LOCATION',
  NUMBER_OF_CONFIRMATION = 'TZ_NUMBER_OF_CONFIRMATION',
  EVENT_DELAY_IN_BLOCKS = 'TZ_EVENT_DELAY_IN_BLOCKS',
  PRIVATE_KEY = 'TZ_PRIVATE_KEY',
  FACTORY_ADDRESS = 'TZ_REGISTRY_ADDRESS',
}

export enum ETH {
  BLOCKCHAIN_PROVIDE_LOCATION = 'ETH_BLOCKCHAIN_PROVIDE_LOCATION',
  PRIVATE_KEY = 'ETH_PRIVATE_KEY',
  CHAIN_ID = 'ETH_CHAIN_ID',
  NUMBER_OF_CONFIRMATION = 'ETH_NUMBER_OF_CONFIRMATION',
  EVENT_DELAY_IN_BLOCKS = 'ETH_EVENT_DELAY_IN_BLOCKS',
  FACTORY_ADDRESS = 'ETH_REGISTRY_ADDRESS',
}
